### ISSUE TITLE
◼️术语表和说明 - VS Code插件创作中文开发文档

### ISSUE THREAD

**Issue by Liiked** [Liiked/VS-Code-Extension-Doc-ZH#77]
https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/ 

 Description

**Comment by Liiked** [comment]
嘿嘿

**Comment by gzhqiang** [comment]
支持支持

**Comment by ddzy** [comment]
> 支持支持

海星海星

**Comment by smart-town** [comment]
一看上面的好像就是来测试的 :wrench:

**Comment by worldzhao** [comment]
tql

**Comment by gitHber** [comment]
请问怎么能够操作 vscode 光标的位置呢？

**Comment by Liiked** [comment]
@gitHber 
你可以试试这个api
https://code.visualstudio.com/api/references/vscode-api#Position

**Comment by HaoboGu** [comment]
问一个无关的问题，网页的主题是在哪里找的呢，感觉看起来很舒服

**Comment by Abbyyan** [comment]
死在第一步，请问会出现`npm install -g yo generator-code`安装一直timeout的情况吗？

**Comment by Abbyyan** [comment]
网页真的好看，尤其是评论后的动态显示

**Comment by Liiked** [comment]
@HaoboGu 这是docsify的vue主题

**Comment by Liiked** [comment]
> 死在第一步，请问会出现`npm install -g yo generator-code`安装一直timeout的情况吗？
> @Abbyyan 

用cnpm试试

**Comment by ddzy** [comment]
> 死在第一步，请问会出现`npm install -g yo generator-code`安装一直timeout的情况吗？

走代理试一下, 实在不行用 cnpm

**Comment by Abbyyan** [comment]
> @ddzy
> > 死在第一步，请问会出现`npm install -g yo generator-code`安装一直timeout的情况吗？
> 
> 走代理试一下, 实在不行用 cnpm

可以了～ 谢谢！感恩～

**Comment by yliangzhao** [comment]
感谢

**Comment by duckbill** [comment]
哇咔咔

**Comment by duckbill** [comment]
很希望能够提供js开发vscode的较差

**Comment by ddzy** [comment]
> 希望能够提供js开发vscode插件的教程。

首先可以参考 [这里](https://github.com/microsoft/vscode-generator-code#run-yo-code) 来生成 js 的插件项目结构

接着将文档里面的 ts 类型声明代码去掉, 就 OK 了

**Comment by joe0110** [comment]
//比方说我写了一个在html中显示css类名的这样一个代码片段，但是在wxml中无法显示
{
    "contributes": {
        "snippets": [
            {
                "language": "html", //比如这里我写的是html，但是无法支持wxml（小程序）的显示
                "path": "./snippets.json"
            }
        ]
    }
}

**Comment by weiwentao518** [comment]
厉害啊

**Comment by guoyanyong** [comment]
请教一个问题，你用vscode做java的开发，现在想写一个插件，插件中如何获取java项目中的所有或指定规则的java源代码呀？希望通过读取源代码中的注释、注解信息分析出文档。

**Comment by weiwentao518** [comment]
为什么我死活打不开“插件发开主机窗口”啊，按F5也没用，只是在上方出现一个调试菜单栏

**Comment by Liiked** [comment]
> @guoyanyong
> 请教一个问题，你用vscode做java的开发，现在想写一个插件，插件中如何获取java项目中的所有或指定规则的java源代码呀？希望通过读取源代码中的注释、注解信息分析出文档。

你可以参考[Language Support for Java(TM) by Red Hat
](https://marketplace.visualstudio.com/items?itemName=redhat.java)还有微软官方的几个插件，而且涉及语言处理的，你可以参考本教程的[语言插件](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/language-extensions/)部分

**Comment by Liiked** [comment]
> @joe0110
> //比方说我写了一个在html中显示css类名的这样一个代码片段，但是在wxml中无法显示
> {
>     "contributes": {
>         "snippets": [
>             {
>                 "language": "html", //比如这里我写的是html，但是无法支持wxml（小程序）的显示
>                 "path": "./snippets.json"
>             }
>         ]
>     }
> }

1. 再增加一组snippets配置，`{
                "language": "wxml",
                "path": "./snippets.json"
            }`
2. 如未生效，检查wxml是否在vsc中注册过，参考[contributes.snippets](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/references/contribution-points?id=contributessnippets)以及[语言标识符](https://code.visualstudio.com/docs/languages/identifiers)

**Comment by pagnkelly** [comment]
虽然文档很清晰了，但是学习起来还是晦涩难懂，一大堆问题得不到结局

**Comment by pagnkelly** [comment]
vscode-languageserver-node 的api文档哪里去看 难道都是一点点看源码的吗

**Comment by Liiked** [comment]
> @pagnkelly
> vscode-languageserver-node 的api文档哪里去看 难道都是一点点看源码的吗

`vscode-languageserver-node`仓库包含了`vscode-languageserver`，也就是[语言服务器](https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/language-extensions/language-server-extension-guide?id=%e4%bb%80%e4%b9%88%e6%98%af39language-server39)小节使用的npm包，具体的api可参考包中的ts类型定义

**Comment by pagnkelly** [comment]
“如果服务器没有运行你还强行添加debbuger的时候“  服务器怎么运行？npm run watch? 针对lsp-sample例子 ，我还是出现这个timeout的错误

**Comment by pagnkelly** [comment]
我可以了

**Comment by yyzybb537** [comment]
请问有vscode插件开发交流群吗？

**Comment by Sir-kaze** [comment]
认识TypeScript-变量和类型-字符串 里面,"模版字符串"应该是"模板".

**Comment by ddzy** [comment]
> 认识TypeScript-变量和类型-字符串 里面,"模版字符串"应该是"模板".

PR 走起

**Comment by qeesung** [comment]
可以可以

**Comment by zkerhcy** [comment]
不错

**Comment by OrangeX4** [comment]
很不错的翻译！

**Comment by AuTsing** [comment]
这个文档太棒了

**Comment by Martin730913** [comment]
`如果我们忽略了这个信息，那就只能提供同样的代码补全项了。`
建议译为
`在这个示例中我们忽略了这个信息，总是提供相同的补全选项`

**Comment by Martin730913** [comment]
> 请问有vscode插件开发交流群吗？

同问

**Comment by Martin730913** [comment]
在server.ts文件中`hasConfigurationCapability` `hasWorkspaceFolderCapability` `hasDiagnosticRelatedInformationCapability`最开始定义的这三个变量是什么意思呢？有什么含义

**Comment by Liiked** [comment]
> `如果我们忽略了这个信息，那就只能提供同样的代码补全项了。`
> 建议译为
> `在这个示例中我们忽略了这个信息，总是提供相同的补全选项`

非常感谢你的建议，我们会在后续版本中修正

**Comment by wyt2000** [comment]
`什么是'Language Client'` 一节的代码注释中：

`// 当文件变动为'.clientrc'中那样时，统治服务器`

`统治`应为`通知`吧。

**Comment by Liiked** [comment]
> `什么是'Language Client'` 一节的代码注释中：
> 
> `// 当文件变动为'.clientrc'中那样时，统治服务器`
> 
> `统治`应为`通知`吧。

非常感谢你的建议，我们会在后续版本中修正

**Comment by janostudio** [comment]
node ./node_modules/vscode/bin/install
这个并不能执行，然后publisher在新的脚手架中消失

**Comment by tamiaO** [comment]
这个文档使用的什么框架生成的哇？

**Comment by qinyalei** [comment]
为什么左侧导航点击没有反应？？

**Comment by jiahaodev** [comment]
支持

**Comment by Ignorance-of-Dong** [comment]
嘿嘿😋

**Comment by hongbing2017** [comment]
?: 是可选的意思吗？之前的变量一节没有讲

**Comment by Liiked** [comment]
> ?: 是可选的意思吗？之前的变量一节没有讲

是可选的意思

**Comment by zflovedota** [comment]
顶顶顶

**Comment by Liiked** [comment]
> ?: 是可选的意思吗？之前的变量一节没有讲

是可选的意思

**Comment by L-cw** [comment]
导航的链接都点不了哇

**Comment by zcfh** [comment]
插件能做到通过命令行运行一个二进制程序吗

**Comment by zrzjohn** [comment]
### 对于初学者来说，术语表根本看不懂。

**Comment by G233** [comment]
## 哈哈哈，很棒，作者加油

**Comment by zq5599966** [comment]
```
481 verbose type range
482 verbose stack @types/vscode: No matching version found for @types/vscode@^1.50.0
482 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:65:11)
482 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
482 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
482 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
482 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
482 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
482 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
482 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
482 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
482 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
482 verbose stack     at runCallback (timers.js:696:18)
482 verbose stack     at tryOnImmediate (timers.js:667:5)
482 verbose stack     at processImmediate (timers.js:649:5)
483 verbose cwd /Users/john/VSExtension/hellovs
484 verbose Darwin 19.5.0
485 verbose argv "/usr/local/Cellar/node/10.3.0/bin/node" "/usr/local/bin/npm" "install" "--cache-min" "86400"
486 verbose node v10.3.0
487 verbose npm  v6.1.0
488 error code ETARGET
489 error notarget No matching version found for @types/vscode@^1.50.0
490 error notarget In most cases you or one of your dependencies are requesting
490 error notarget a package version that doesn't exist.
490 error notarget
490 error notarget It was specified as a dependency of 'hellovs'
491 verbose exit [ 1, true ]
```
初始化就挂了……

**Comment by Pines-Cheng** [comment]
非常赞

**Comment by zerotower69** [comment]
牛啊

**Comment by Lurenlzm** [comment]
赞

**Comment by WakerCN** [comment]
厉害了

**Comment by WakerCN** [comment]
怎么把本地文件一个目录下内容在视图下面显示出来呀

**Comment by Liiked** [comment]
> 怎么把本地文件一个目录下内容在视图下面显示出来呀

可以具体描述一下你的场景

**Comment by chengandguo** [comment]
不想用ts的话，js开发也是可以的

**Comment by WakerCN** [comment]
弹出框中重启添加重启按钮vscode这个该使用什么api

**Comment by yq121** [comment]
踩踩

**Comment by fengmumu1** [comment]
感谢翻译的大佬

**Comment by gepingli** [comment]
感谢大佬的翻译！！

**Comment by neil-ji** [comment]
> 这风格太喜欢了，想搬到自己博客上去

鼎力支持~

## 鼎力支持~

* 鼎力支持~

1 鼎力支持~

```javascript
console.log("鼎力支持~")

**Comment by G233** [comment]
很有帮助，谢谢博主

**Comment by zflovedota** [comment]
很NICE！

**Comment by RFC2109** [comment]
嘿嘿嘿

**Comment by ytx222** [comment]
TF400898: An Internal Error Occurred. Activity Id: da1402ab-d09d-4ed8-8794-5c5f929dc46b.
有人知道我遇到是什么问题吗,
如果知道,联系1146918232@qq.com,红包感谢

**Comment by itLeeyw** [comment]
很棒！

**Comment by thisNiBi** [comment]
这个好厉害

**Comment by fakeou** [comment]
###真不错

**Comment by xuexiansen123** [comment]
首先非常感谢大佬们无私分享，这里我请教一个问题：在进行 vscode 插件开发中，采用TypeScript语言，是否支持间接调用python脚本？多多感谢，联系 1256786368@qq.com

**Comment by zainosl** [comment]
hello

**Comment by Zenser** [comment]
翻译工作者辛苦啦~~

**Comment by bingoAO** [comment]
即将开始人生中第一个vscode helloworld，哈哈哈

**Comment by daixyc** [comment]
学习学习

**Comment by youngjuning** [comment]
```rust
println("同款评论系统~")
```

**Comment by L1114** [comment]
666

**Comment by ajunzai** [comment]
NICE

**Comment by qiuchenjun** [comment]
支持

**Comment by wuliupo** [comment]
> @Abbyyan
> 死在第一步，请问会出现`npm install -g yo generator-code`安装一直timeout的情况吗？

npm install -g yo generator-code --registry=http://registry.npm.taobao.org

**Comment by kingkingki** [comment]
“有些事件可能从不稳定的变化状态开始，而随着状态变化这一事件最后肯能被取消了。”这句话有错别字：
最后的“肯能”=》 “可能”？

**Comment by misszhao1998** [comment]
好点有点云里雾里

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by lzw10168** [comment]
为什么我只能看术语表和说明文档 。其它都看不了

**Comment by windyoung1990** [comment]
概念好难理解啊

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by mounwater** [comment]
测试

**Comment by mounwater** [comment]
评论完的动画不错

**Comment by mounwater** [comment]
留个言开启vscode插件开发之路~

**Comment by SmileSmith** [comment]
🐂

**Comment by Bingo14112198** [comment]
test

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by duckbill** [comment]
可爱的朋友，我最近很忙！收到你的祝福令我很开心，谢谢你哦！我会尽快回复的哦

**Comment by prince12138** [comment]
고마워요 고마워요

**Comment by 20094921** [comment]
大佬们，有群吗，我想做一个插件自动更新的功能，由于是内网没有插件市场，所以想的是弹框让用户点击，然后后面的思路就不清楚了，可以讲解一下吗

**Comment by baniyasi** [comment]
大佬求问，仅仅在language-configuration.json里加了中文括号的自动补充，我在F5调试的时候是好的，但是打包成.vsix后再安装插件，输入中文括号就没反应了

**Comment by Resist4263** [comment]
有人遇到过mac安装Yeoman时出现lchown /usr/local/bin/sentinelctl出现权限禁止的问题吗？我试过去恢复模式用csrutil disable之后还是不行

**Comment by ziyi2** [comment]
11

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by bianlin** [comment]
踩个坑

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by Lukrisum** [comment]
支持支持

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by MeteorGeminy** [comment]
👍🏻

**Comment by Nick955** [comment]
nice

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by Mabrocun** [comment]
支持

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by goddnsgit** [comment]
谢谢你.非常感谢.

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by 13753013227** [comment]
赞👍

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by baohangxing** [comment]
支持支持

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by zhaozhihao59** [comment]
hello world 运行以后，在命令输入框中找不到这个Hello World 命令，求解

我已经解决了。感谢，因为我的版本不是最新的。所以有点问题

**Comment by easyGao-eleven** [comment]
nice

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by LonelyDrifter** [comment]
我看看评论之后的特效

**Comment by jiangnana** [comment]
卡在了第二步，在命令面板(Ctrl+Shift+P)中输入Hello World命令，显示没有匹配的命令

**Comment by jiangnana** [comment]
> @zhaozhihao59
> hello world 运行以后，在命令输入框中找不到这个Hello World 命令，求解
> 
> 我已经解决了。感谢，因为我的版本不是最新的。所以有点问题

是什么的版本不是最新的

**Comment by syccxdr** [comment]
不错！

**Comment by Angus-Liu** [comment]
感谢大大！刚好要写一个插件，学习啦！

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by YangYongAn** [comment]
这个 WebView 是否可以再开启 devtools

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by xiaoxiaofei2016** [comment]
感谢作者，文档很棒！

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by forlaugh** [comment]
> 卡在了第二步，在命令面板(Ctrl+Shift+P)中输入Hello World命令，显示没有匹配的命令

可能是这个问题: 调试窗口的输出里面有报错，需要更新vscode版本。我的1.76.2也没有指令，更新到最新就可以了

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by onlytailei** [comment]
支持一个  给力哦

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by transitiongo** [comment]
111

**Comment by transitiongo** [comment]
11111

**Comment by transitiongo** [comment]
1

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by GellenLiu** [comment]
nice

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by bluebear4** [comment]
请问一下 在命令面板 如何传参给自己注册的命令

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by qq253498229** [comment]
好人一生平安，一胎生八个

**Comment by wangmeijian** [comment]
https://liiked.github.io/VS-Code-Extension-Doc-ZH/#/extension-guides/tree-view 图片挂了

**Comment by seamanwarm** [comment]
图片显示不出来 难受

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by AdamZero** [comment]
**支持支持**

**Comment by YuanDaoDao001** [comment]
评论看看动效，顺便问一嘴，文档还在更新吗

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by Liiked** [comment]
> @YuanDaoDao001
> 评论看看动效，顺便问一嘴，文档还在更新吗

会更新的，最近一段时间都比较忙，不好意思

**Comment by githubhwen** [comment]
> @Abbyyan
> 死在第一步，请问会出现`npm install -g yo generator-code`安装一直timeout的情况吗？

不会

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by sailthesea** [comment]
请问一下如果我需要在vscode里面集成远端的websocket通讯的LSP服务，可以实现这个插件吗？

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by shilohooo** [comment]
```csharp
Console.WriteLine("six six six");
```

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by YMYzzz** [comment]
很好地教程，不过有些图片挂了

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by YLifeOnlyOnce** [comment]
> @Abbyyan
> 网页真的好看，尤其是评论后的动态显示

我单纯试试动态展示[狗头]

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by Jlnvv-tom** [comment]
什么插件文档留言

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by guosen001** [comment]
动态展示?没见过我也试试

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by linnene** [comment]
我嘞个豆，这个输入字体真不错

**Comment by hapilou516** [comment]
为什么这个页面有些图片都挂掉了

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。

**Comment by YMYzzz** [comment]
需要看视频的可以去英文官网看

**Comment by bingoAO** [comment]
你好，你的邮件已收到，我会尽快查看。
